---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
<<<<<<< HEAD
<<<<<<< HEAD
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive
=======
  - npm config set spin false
>>>>>>> 0b7cfbf... message
=======
  - npm config set spin false
>>>>>>> 17df8ae... message

script:
  - yarn lint:hbs
  - yarn lint:js
  - yarn test
